carrental/carrental/urls.py
from django.contrib import admin
from django.urls import path, include
from carrental import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('exit/', views.LogOutPage.as_view(), name='exit'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cars/', include('cars.urls')),
    path('about/', views.AboutView.as_view(), name='about'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

carrental/cars/urls.py
from django.contrib import admin


from django.urls import path
from .views import (car_list_view, car_view, BookingView, BookingListView, add_comment_to_car, AllCarsListView, CancelBookingView)

app_name = 'cars'

urlpatterns = [
    path('<int:pk>', car_view, name = "detail"),
    path('booking/<int:pk>', BookingView.as_view(), name = "booking"),
    path('booking_list', BookingListView.as_view(), name = "booking_list"),
    path('all_cars_list', AllCarsListView.as_view(), name = "all_cars_list"),
    path('car_list', car_list_view, name = "list"),
    path('<int:pk>/d+/comment/', add_comment_to_car, name='add_comment_to_car'),
    path('booking/cancel/<int:pk>',CancelBookingView.as_view(),name="CancelBookingView"),
]

carrental/cars/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from django.contrib.auth import get_user_model
User = get_user_model()


class CarMain(models.Model):
    brand = models.CharField(max_length=16)
    model = models.CharField(max_length=32)

    def __str__(self):
        return f"{self.brand} {self.model}"

class CarDetail(models.Model):
    CAR_COLORS = [
        ("RED", "Red"),
        ("BLU", "Blue"),
        ("YEL", "Yellow"),
        ("BLA", "Black"),
        ("WHI", "White")
    ]
    CAR_FUELS = [
        ("DIE", "Diesel"),
        ("PET", "Petrol"),
        ("HYB", "Hybrid"),
        ("LPG", "LPG"),
        ("ELE", "Electric"),
    ]
    production_date = models.DateField()
    color = models.CharField(max_length=3, choices=CAR_COLORS)
    seats = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(9)])
    fuel = models.CharField(max_length=3, choices=CAR_FUELS)
    power = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(0.00)])

    def __str__(self):
        return f"prod_date:{self.production_date},color : {self.color},seats : {self.seats},fuel : {self.fuel},power : {self.power},price : {self.price}"

class Car(models.Model):
    main = models.ForeignKey(CarMain, on_delete=models.CASCADE)
    detail = models.OneToOneField(CarDetail, on_delete=models.PROTECT)
    image = models.ImageField(blank=True, null=True)

    def delete(self):
        super(Car, self).delete()
        self.detail.delete()

    def __str__(self):
        return f"{self.main.brand} {self.main.model}"

class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()

    def __str__(self):
        return f"{self.user} has booked {self.car} from {self.check_in} to {self.check_out}"

    def get_cancel_booking_url(self):
        return reverse_lazy('cars:CancelBookingView',args=[self.pk])

class Comment(models.Model):
    car = models.ForeignKey('cars.Car', related_name='comment', on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now())

    def get_absolute_url(self):
        return reverse('cars:list')

    def __str__(self):
        return self.text

carrental/cars/forms.py
from .models import Car, CarDetail, CarMain, Comment
from django.forms import ModelForm, DateInput
from django import forms
from django.core.validators import MinValueValidator

class CarForm(ModelForm):
    class Meta:
        model = Car
        fields = ['main', 'detail']


class CarDetailForm(ModelForm):
    production_date_start = forms.DateField(widget=DateInput(
                format=('%d/%m/%Y'),
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Select a date',
                    'type': 'date',}
            ))
    production_date_end = forms.DateField(widget=DateInput(
                format=('%d/%m/%Y'),
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Select a date',
                    'type': 'date',}
            ))
    power_min = forms.IntegerField(min_value=0)
    power_max = forms.IntegerField(min_value=0)
    price_min = forms.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(0.00)])
    price_max = forms.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(0.00)])

    class Meta:
        model = CarDetail
        exclude = ('car', 'power', 'production_date', 'price')


    def __init__(self, *args, **kwargs):
        super(CarDetailForm, self).__init__(*args, **kwargs)
        self.fields['color'].required = False
        self.fields['seats'].required = False
        self.fields['fuel'].required = False
        self.fields['production_date_end'].required = False
        self.fields['production_date_start'].required = False
        self.fields['power_min'].required = False
        self.fields['power_max'].required = False
        self.fields['price_min'].required = False
        self.fields['price_max'].required = False

class CarMainForm(ModelForm):
    class Meta:
        model = CarMain
        exclude = ('car', )

    def __init__(self, *args, **kwargs):
        super(CarMainForm, self).__init__(*args, **kwargs)
        self.fields['model'].required = False
        self.fields['brand'].required = False

class AvailabilityForm(forms.Form):
    check_in = forms.DateTimeField(widget=DateInput(
                                    format=('%d/%m/%Y'),
                                    attrs = {
                                        'class': 'form-control',
                                        'placeholder': 'Select a date',
                                        'type': 'date', }
                                    ))
    check_out = forms.DateTimeField(widget=DateInput(
                                    format=('%d/%m/%Y'),
                                    attrs = {
                                        'class': 'form-control',
                                        'placeholder': 'Select a date',
                                        'type': 'date', }
                                    ))

class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('author', 'text')

        widgets = {
            'author':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea'}),
        }

carrental/cars/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect, HttpResponseRedirect
from django.views.generic import ListView, FormView, DeleteView
from .models import Car, Booking
from .forms import AvailabilityForm, CarDetailForm, CarMainForm, CommentForm
from .booking_functions.availability import check_availability
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

def car_list_view(request):
    context = {}
    template = "car_list.html"
    if request.method == 'GET':
        car_detail_form = CarDetailForm(prefix='detail')
        car_main_form = CarMainForm(prefix='main')
        context["car_detail_form"] = car_detail_form
        context["car_main_form"] = car_main_form
        return render(request, template, context)
    if request.method == "POST":
        cars = Car.objects.select_related("main").select_related("detail").all()
        car_detail_form = CarDetailForm(request.POST, prefix='detail')
        car_main_form = CarMainForm(request.POST, prefix='main')
        if car_detail_form.is_valid() and car_main_form.is_valid():
            brand = car_main_form.cleaned_data['brand']
            if brand:
                cars = cars.filter(main__brand=brand)

            model = car_main_form.cleaned_data['model']
            if model:
                cars = cars.filter(main__model=model)

            #detail
            color = car_detail_form.cleaned_data['color']
            if color:
                cars = cars.filter(detail__color=color)

            seats = car_detail_form.cleaned_data['seats']
            if seats:
                cars = cars.filter(detail__seats=seats)

            fuel = car_detail_form.cleaned_data['fuel']
            if fuel:
                cars = cars.filter(detail__fuel=fuel)


            power_min = car_detail_form.cleaned_data['power_min']
            power_max = car_detail_form.cleaned_data['power_max']
            if power_min:
                cars = cars.filter(detail__power__gte=power_min)
            if power_max:
                cars = cars.filter(detail__power__lte=power_max)

            price_min = car_detail_form.cleaned_data['price_min']
            price_max = car_detail_form.cleaned_data['price_max']
            if price_min:
                cars = cars.filter(detail__price__gte=price_min)
            if price_max:
                cars = cars.filter(detail__price__lte=price_max)


            production_date_start = car_detail_form.cleaned_data['production_date_start']
            production_date_end = car_detail_form.cleaned_data['production_date_end']
            if production_date_start:
                cars = cars.filter(detail__production_date__gte=production_date_start)
            if production_date_end:
                cars = cars.filter(detail__production_date__lte=production_date_end)


        context['cars'] = cars
        print(cars)
        context["car_detail_form"] = car_detail_form
        context["car_main_form"] = car_main_form
        return render(request, template, context)

def car_view(request, pk):
    template="car_detail.html"
    context={}
    if request.method == "GET":
        car = Car.objects.get(id=pk)
        context['car'] = car
        return render(request, template, context)


class AllCarsListView(ListView):
    model = Car
    template_name = "all_cars_list.html"
    def get_query_set(self,*args,**kwargs):
        car_list = Booking.objects.all()
        return car_list


class BookingListView(ListView):
    model = Booking
    template_name = "booking_list.html"
    def get_query_set(self,*args,**kwargs):
        booking_list = Booking.objects.filter(user=self.request.user)
        return booking_list

class BookingView(FormView):
    form_class = AvailabilityForm
    template_name = 'car_booking.html'

    def form_valid(self, form):
        data = form.cleaned_data
        car_list = Car.objects.select_related("main").select_related("detail").all()
        for car in car_list:
            if check_availability(car, data['check_in'],data['check_out']):

                booking = Booking.objects.create(
                    user = self.request.user,
                    car = car,
                    check_in = data['check_in'],
                    check_out = data['check_out'],
                )
                booking.save()
                return HttpResponse("<h2><a href='http://eughrat.pythonanywhere.com/'>Your booking has been confirmed, click to return to home page</a></h2>")
            else:
                return HttpResponse("<h2><a href='http://eughrat.pythonanywhere.com/'>This car is already booked, click to return to home page</a></h2>")

class CancelBookingView(DeleteView):
    model = Booking
    template_name = 'booking_cancel_view.html'
    success_url = reverse_lazy('cars:booking_list')

@login_required
def add_comment_to_car(request, pk):
    car = get_object_or_404(Car,pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.car = car
            comment.save()
            return redirect('cars:detail',pk=car.pk)
    else:
        form = CommentForm()
    return render(request,'cars/comment_form.html',{'form':form})

carrental/cars/templates/all_cars_list.html
{% extends "car_base.html" %}

{% block car_content %}

<h1>Our cars offer</h1>
<h2><a href="{% url 'cars:list' %}"> Advanced Search </a></h2>


<div class="list-content">
    {% for car in car_list %}
        <div class="car">
            <div>
                <a class href="{% url 'cars:detail' car.id %}">
                    {% if car.image %}
                        <img src="{{ car.image.url}}">
                    {% endif %}
                        <h2>{{car.main.brand}} {{ car.main.model }}</h2>
                        <p>Color: {{ car.detail.get_color_display }}</p>
                        <p>No of seats: {{ car.detail.seats }}</p>
                        <p>Fuel type: {{ car.detail.get_fuel_display }}</p>
                        <p>Engine power:{{ car.detail.power }}</p>
                        <p>Prod. date: {{ car.detail.production_date }}</p>
                        <p>Price: {{ car.detail.price }} /24h</p>
                </a>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock car_content %}

carrental/cars/templates/booking_cancel_view.html
{% extends 'base.html' %}

{% block content %}

<div class="list-content">
    <h1>Are you sure to resign ?</h1>
    <div class="car-detail" >
        <form id="booking-form" action="" method="POST">
            {% csrf_token %}
                <h2>Brand: {{booking.car}}</h2>
                <p>Pick-up: {{booking.check_in}}</p>
                <p>Drop-off: {{booking.check_out}}</p>
                <button class="btn btn-primary btn-comment" type="submit">Resign</button>
        </form>
    </div>
</div>

{% endblock content %}

carrental/cars/templates/car_base.html
{% extends 'base.html' %}

{% block content %}

        <div class="row">
            {% block car_content %}{% endblock %}
        </div>

{% endblock %}

carrental/cars/templates/car_booking.html
{% extends "car_base.html" %}
{% load bootstrap3 %}
{% block car_content %}

<h1>Confirm your booking</h1>

<div class="login-page">
    <form id="booking-form" action="" method="POST" class="post-form">

        {% csrf_token %}
        {% bootstrap_form form %}
         <a href="{% url 'cars:booking_list'%}"><button type="submit" class="save btn btn-default">Book</button></a>
    </form>
</div>

{% endblock car_content %}

carrental/cars/templates/car_detail.html
{% extends "car_base.html" %}
{% load static %}
{% block car_content %}


<div class="square">
    <div class="car-detail">
        <h2>{{car}}</h2>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
            numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
            veniam,
            rerum repellendus magnam labore.
        </p>
        <p>Color: {{ car.detail.get_color_display }}</p>
        <p>No of seats: {{ car.detail.seats }}</p>
        <p>Fuel type: {{ car.detail.get_fuel_display }}</p>
        <p>Engine power:{{ car.detail.power }}</p>
        <p>Prod. date: {{ car.detail.production_date }}</p>
        <p>Price: {{ car.detail.price }} /24h</p>
        {% if user.is_authenticated %}
            <a class="btn btn-primary btn-comment" href="{% url 'cars:booking' car.id %}">Book a car</a>
        {% endif %}
            <a class="btn btn-primary btn-comment" href="{% url 'cars:add_comment_to_car' pk=car.pk %}">Add comment</a>
    </div>
</div>

<div class="square">
    {% if car.image %}
        <img src="{{ car.image.url}}" alt="cant load media">
    {% endif %}
</div>

<div style="clear: both;"></div>

<div class="line"></div>

<div class="comments">
    <h3>Comments:</h3>
    {% for comment in car.comment.all %}
    <br>
    {{ comment.created_date }}
    <p>{{comment.text}}</p>
    <p>Created at: {{ comment.create_date|date:'d-m-y' }}</p>
    <p>Author:{{comment.author}}</p>
    {% empty %}
    <p>No Comments!</p>
    {% endfor %}
</div>


{% endblock car_content %}

carrental/cars/templates/car_list.html
{% extends "car_base.html" %}
{% load static %}
{% load bootstrap3 %}
{% block car_content %}

<div class="sidebar">
    <div class class="login-page">
        <form method="post" class="post-form">
            <button type="submit" class="save btn btn-default">Search</button>
            </br></br>
            {% csrf_token %}
                <table>
                    {% bootstrap_form car_main_form %}
                    {% bootstrap_form car_detail_form %}
                </table>
        </form>
    </div>
</div>
<div class="list-content">
    {% for car in cars %}
        <div class="car">
            <div>
                <a class href="{% url 'cars:detail' car.id %}">
                    {% if car.image %}
                        <img src="{{ car.image.url}}">
                    {% endif %}
                        <h2>{{car.main.brand}} {{ car.main.model }}</h2>
                        <p>Color: {{ car.detail.get_color_display }}</p>
                        <p>No of seats: {{ car.detail.seats }}</p>
                        <p>Fuel type: {{ car.detail.get_fuel_display }}</p>
                        <p>Engine power:{{ car.detail.power }}</p>
                        <p>Prod. date: {{ car.detail.production_date }}</p>
                        <p>Price: {{ car.detail.price }} /24h</p>
                </a>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock car_content %}