carrental/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

carrental/carrental/urls.py
from django.contrib import admin
from django.urls import path, include
from carrental import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('exit/', views.LogOutPage.as_view(), name='exit'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cars/', include('cars.urls')),
    path('about/', views.AboutView.as_view(), name='about'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

carrental/cars/urls.py
from django.contrib import admin


from django.urls import path
from .views import (car_list_view, car_view, BookingView, BookingListView, add_comment_to_car, AllCarsListView, CancelBookingView)

app_name = 'cars'

urlpatterns = [
    path('<int:pk>', car_view, name = "detail"),
    path('booking/<int:pk>', BookingView.as_view(), name = "booking"),
    path('booking_list', BookingListView.as_view(), name = "booking_list"),
    path('all_cars_list', AllCarsListView.as_view(), name = "all_cars_list"),
    path('car_list', car_list_view, name = "list"),
    path('<int:pk>/d+/comment/', add_comment_to_car, name='add_comment_to_car'),
    path('booking/cancel/<int:pk>',CancelBookingView.as_view(),name="CancelBookingView"),
]

carrental/templates/about.html
{% extends 'base.html' %}

{% block content %}
<div class="landing-page">
    <h1>About us</h1>
</div>
{% endblock %}

carrental/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Piernicki Car Rental</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>

<body>

<nav class="navbar mynav" role="navigation" id="navbar">
    <div class="container">
        <a class="navbar-brand mynav" href="{% url 'home' %}" id="navbar-home">Piernicki Rent</a>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'cars:booking_list' %}">Manage booking</a></li>
                <li><a href="{% url 'cars:all_cars_list' %}">Our offer</a></li>
                <li><a href="{% url 'about' %}">About us</a></li>
                <li><a href="{% url 'cars:list' %}">Search</a></li>
                <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
            {% else %}
                <li><a href="{% url 'cars:all_cars_list' %}">Our Offer</a></li>
                <li><a href="{% url 'about' %}">About us</a></li>
                <li><a href="{% url 'cars:list' %}">Search</a></li>
                <li><a href="{% url 'accounts:login' %}">Log in</a></li>
                <li><a href="{% url 'accounts:signup' %}">Sign in</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="content container">

    {% block content %}

    {% endblock %}

</div>

</body>

</html>

carrental/templates/exit.html
{% extends 'base.html' %}

{% block content %}
<div class="landing-page">
    <h1>You are logged out!</h1>
</div>
{% endblock %}

carrental/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="landing-page">
    <h1>Welcome to Piernicki Rent {{user.username}}!</h1>
</div>
{% endblock %}